<!DOCTYPE html>
<html>
<head>
<link rel="icon" type="image/x-icon" href="assets/img/AirMinumku.png" />
<title>Masukkan Data Template</title>
<style>
h1, table {
border-collapse: collapse;
width: 100%;
color: #588c7e;
font-family: monospace;
font-size: 25px;
text-align: left;
}
th {
background-color: #588c7e;
color: white;
}
.button {
border: none;
color: white;
padding: 15px 32px;
text-align: center;
text-decoration: none;
display: inline-block;
font-size: 16px;
margin: 4px 2px;
cursor: pointer;
}
.button1 {background-color: #588c7e;} /* Green */
tr:nth-child(even) {background-color: #f2f2f2}
</style>
</head>

<body>
<h1>Memasukkan Data Template</h1>
<button class="button button1" onclick="location.href = 'index.html';">Kembali ke Halaman Utama</button>
<br>
<?php
$conn = mysqli_connect("localhost:8111", "root", "1234", "airminumku");
// Check connection
if ($conn->connect_error) {
die("Connection failed: " . $conn->connect_error);
}
$sql = "DROP TABLE airminum;

CREATE TABLE airminum 
(
    kecamatan	varchar(30),
    desa	varchar(30),
    sumber	varchar(30),
    jumlah	int,
    satuan	varchar(10),
    tahun	year
);

INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN WADO', 'DESA CIKAREO SELATAN', 'Air kemasan bermerek', '6', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN WADO', 'DESA CIKAREO SELATAN', 'Air sungan/danau/waduk', '1', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN WADO', 'DESA CIKAREO SELATAN', 'Lainnya', '5', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN WADO', 'DESA CIKAREO SELATAN', 'Air isi ulang', '207', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN WADO', 'DESA CIKAREO SELATAN', 'Leding eceran', '1', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN WADO', 'DESA CIKAREO SELATAN', 'Sumur bor/pompa', '4', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN WADO', 'DESA CIKAREO SELATAN', 'Sumur terlindung', '50', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN WADO', 'DESA CIKAREO SELATAN', 'Sumur tak terlindung', '48', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN WADO', 'DESA CIKAREO SELATAN', 'Mata air terlindung', '1056', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN WADO', 'DESA CIKAREO SELATAN', 'Mata air tak terlindung', '26', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN WADO', 'DESA CIKAREO UTARA', 'Air kemasan bermerek', '16', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN WADO', 'DESA CIKAREO UTARA', 'Air hujan', '1', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN WADO', 'DESA CIKAREO UTARA', 'Lainnya', '2', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN WADO', 'DESA CIKAREO UTARA', 'Air isi ulang', '846', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN WADO', 'DESA CIKAREO UTARA', 'Leding meteran', '82', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN WADO', 'DESA CIKAREO UTARA', 'Leding eceran', '42', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN WADO', 'DESA CIKAREO UTARA', 'Sumur bor/pompa', '50', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN WADO', 'DESA CIKAREO UTARA', 'Sumur terlindung', '120', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN WADO', 'DESA CIKAREO UTARA', 'Sumur tak terlindung', '7', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN WADO', 'DESA CIKAREO UTARA', 'Mata air terlindung', '86', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN WADO', 'DESA CIKAREO UTARA', 'Mata air tak terlindung', '29', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN WADO', 'DESA CIMUNGKAL', 'Air isi ulang', '1', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN WADO', 'DESA CIMUNGKAL', 'Sumur terlindung', '104', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN WADO', 'DESA CIMUNGKAL', 'Sumur tak terlindung', '6', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN WADO', 'DESA CIMUNGKAL', 'Mata air terlindung', '527', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN WADO', 'DESA CIMUNGKAL', 'Mata air tak terlindung', '95', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN WADO', 'DESA CISURAT', 'Leding meteran', '4', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN WADO', 'DESA CISURAT', 'Sumur terlindung', '72', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN WADO', 'DESA CISURAT', 'Sumur tak terlindung', '1', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN WADO', 'DESA CISURAT', 'Mata air terlindung', '1094', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN WADO', 'DESA CISURAT', 'Mata air tak terlindung', '4', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN WADO', 'DESA GANJARRESIK', 'Air kemasan bermerek', '1', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN WADO', 'DESA GANJARRESIK', 'Air sungan/danau/waduk', '74', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN WADO', 'DESA GANJARRESIK', 'Lainnya', '26', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN WADO', 'DESA GANJARRESIK', 'Air isi ulang', '92', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN WADO', 'DESA GANJARRESIK', 'Leding meteran', '12', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN WADO', 'DESA GANJARRESIK', 'Sumur bor/pompa', '3', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN WADO', 'DESA GANJARRESIK', 'Sumur terlindung', '13', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN WADO', 'DESA GANJARRESIK', 'Sumur tak terlindung', '14', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN WADO', 'DESA GANJARRESIK', 'Mata air terlindung', '302', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN WADO', 'DESA GANJARRESIK', 'Mata air tak terlindung', '292', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN WADO', 'DESA MULYAJAYA', 'Lainnya', '6', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN WADO', 'DESA MULYAJAYA', 'Air isi ulang', '3', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN WADO', 'DESA MULYAJAYA', 'Leding eceran', '1', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN WADO', 'DESA MULYAJAYA', 'Sumur bor/pompa', '26', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN WADO', 'DESA MULYAJAYA', 'Sumur terlindung', '25', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN WADO', 'DESA MULYAJAYA', 'Sumur tak terlindung', '4', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN WADO', 'DESA MULYAJAYA', 'Mata air terlindung', '980', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN WADO', 'DESA MULYAJAYA', 'Mata air tak terlindung', '11', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN WADO', 'DESA SUKAJADI', 'Lainnya', '1', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN WADO', 'DESA SUKAJADI', 'Air isi ulang', '3', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN WADO', 'DESA SUKAJADI', 'Leding meteran', '38', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN WADO', 'DESA SUKAJADI', 'Leding eceran', '7', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN WADO', 'DESA SUKAJADI', 'Sumur bor/pompa', '1', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN WADO', 'DESA SUKAJADI', 'Sumur terlindung', '25', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN WADO', 'DESA SUKAJADI', 'Sumur tak terlindung', '7', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN WADO', 'DESA SUKAJADI', 'Mata air terlindung', '1024', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN WADO', 'DESA SUKAJADI', 'Mata air tak terlindung', '10', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN WADO', 'DESA SUKAPURA', 'Air kemasan bermerek', '7', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN WADO', 'DESA SUKAPURA', 'Lainnya', '8', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN WADO', 'DESA SUKAPURA', 'Air isi ulang', '48', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN WADO', 'DESA SUKAPURA', 'Leding meteran', '158', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN WADO', 'DESA SUKAPURA', 'Leding eceran', '5', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN WADO', 'DESA SUKAPURA', 'Sumur bor/pompa', '2', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN WADO', 'DESA SUKAPURA', 'Sumur terlindung', '6', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN WADO', 'DESA SUKAPURA', 'Sumur tak terlindung', '5', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN WADO', 'DESA SUKAPURA', 'Mata air terlindung', '720', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN WADO', 'DESA SUKAPURA', 'Mata air tak terlindung', '29', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN WADO', 'DESA CILENGKRANG', 'Air sungan/danau/waduk', '2', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN WADO', 'DESA CILENGKRANG', 'Air isi ulang', '10', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN WADO', 'DESA CILENGKRANG', 'Sumur terlindung', '114', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN WADO', 'DESA CILENGKRANG', 'Sumur tak terlindung', '8', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN WADO', 'DESA CILENGKRANG', 'Mata air terlindung', '1756', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN WADO', 'DESA CILENGKRANG', 'Mata air tak terlindung', '19', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGMEDAR', 'DESA WARGALUYU', 'Air kemasan bermerek', '1', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGMEDAR', 'DESA WARGALUYU', 'Air sungan/danau/waduk', '2', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGMEDAR', 'DESA WARGALUYU', 'Air isi ulang', '83', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGMEDAR', 'DESA WARGALUYU', 'Sumur terlindung', '70', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGMEDAR', 'DESA WARGALUYU', 'Sumur tak terlindung', '42', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGMEDAR', 'DESA WARGALUYU', 'Mata air terlindung', '737', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGMEDAR', 'DESA WARGALUYU', 'Mata air tak terlindung', '93', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGMEDAR', 'DESA TANJUNGWANGI', 'Lainnya', '27', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGMEDAR', 'DESA TANJUNGWANGI', 'Leding meteran', '1', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGMEDAR', 'DESA TANJUNGWANGI', 'Sumur terlindung', '18', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGMEDAR', 'DESA TANJUNGWANGI', 'Sumur tak terlindung', '1', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGMEDAR', 'DESA TANJUNGWANGI', 'Mata air terlindung', '323', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGMEDAR', 'DESA TANJUNGWANGI', 'Mata air tak terlindung', '11', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGMEDAR', 'DESA TANJUNGMEDAR', 'Air isi ulang', '1', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGMEDAR', 'DESA TANJUNGMEDAR', 'Sumur bor/pompa', '1', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGMEDAR', 'DESA TANJUNGMEDAR', 'Sumur terlindung', '246', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGMEDAR', 'DESA TANJUNGMEDAR', 'Sumur tak terlindung', '8', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGMEDAR', 'DESA TANJUNGMEDAR', 'Mata air terlindung', '91', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGMEDAR', 'DESA SUKATANI', 'Air isi ulang', '16', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGMEDAR', 'DESA SUKATANI', 'Sumur bor/pompa', '7', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGMEDAR', 'DESA SUKATANI', 'Sumur terlindung', '316', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGMEDAR', 'DESA SUKATANI', 'Sumur tak terlindung', '25', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGMEDAR', 'DESA SUKATANI', 'Mata air terlindung', '142', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGMEDAR', 'DESA SUKATANI', 'Mata air tak terlindung', '43', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGMEDAR', 'DESA SUKAMUKTI', 'Air kemasan bermerek', '3', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGMEDAR', 'DESA SUKAMUKTI', 'Lainnya', '2', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGMEDAR', 'DESA SUKAMUKTI', 'Air isi ulang', '293', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGMEDAR', 'DESA SUKAMUKTI', 'Sumur bor/pompa', '12', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGMEDAR', 'DESA SUKAMUKTI', 'Sumur terlindung', '94', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGMEDAR', 'DESA SUKAMUKTI', 'Mata air terlindung', '9', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGMEDAR', 'DESA KERTAMUKTI', 'Sumur bor/pompa', '27', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGMEDAR', 'DESA KERTAMUKTI', 'Sumur terlindung', '542', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGMEDAR', 'DESA KERTAMUKTI', 'Sumur tak terlindung', '7', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGMEDAR', 'DESA KERTAMUKTI', 'Mata air terlindung', '375', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGMEDAR', 'DESA KERTAMUKTI', 'Mata air tak terlindung', '41', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGMEDAR', 'DESA KAMAL', 'Leding meteran', '2', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGMEDAR', 'DESA KAMAL', 'Sumur bor/pompa', '3', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGMEDAR', 'DESA KAMAL', 'Sumur terlindung', '64', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGMEDAR', 'DESA KAMAL', 'Sumur tak terlindung', '1', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGMEDAR', 'DESA KAMAL', 'Mata air terlindung', '77', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGMEDAR', 'DESA JINGKANG', 'Air kemasan bermerek', '1', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGMEDAR', 'DESA JINGKANG', 'Air hujan', '1', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGMEDAR', 'DESA JINGKANG', 'Air isi ulang', '60', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGMEDAR', 'DESA JINGKANG', 'Leding meteran', '7', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGMEDAR', 'DESA JINGKANG', 'Sumur terlindung', '287', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGMEDAR', 'DESA JINGKANG', 'Sumur tak terlindung', '46', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGMEDAR', 'DESA JINGKANG', 'Mata air terlindung', '154', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGMEDAR', 'DESA JINGKANG', 'Mata air tak terlindung', '26', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGMEDAR', 'DESA CIKARAMAS', 'Air isi ulang', '24', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGMEDAR', 'DESA CIKARAMAS', 'Leding meteran', '1', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGMEDAR', 'DESA CIKARAMAS', 'Leding eceran', '1', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGMEDAR', 'DESA CIKARAMAS', 'Sumur bor/pompa', '2', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGMEDAR', 'DESA CIKARAMAS', 'Sumur terlindung', '390', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGMEDAR', 'DESA CIKARAMAS', 'Sumur tak terlindung', '16', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGMEDAR', 'DESA CIKARAMAS', 'Mata air terlindung', '207', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGMEDAR', 'DESA CIKARAMAS', 'Mata air tak terlindung', '5', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN JATINUNGGAL', 'DESA SIRNASARI', 'Air kemasan bermerek', '2', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN JATINUNGGAL', 'DESA SIRNASARI', 'Air sungan/danau/waduk', '1', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN JATINUNGGAL', 'DESA SIRNASARI', 'Lainnya', '7', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN JATINUNGGAL', 'DESA SIRNASARI', 'Air isi ulang', '101', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN JATINUNGGAL', 'DESA SIRNASARI', 'Leding meteran', '361', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN JATINUNGGAL', 'DESA SIRNASARI', 'Leding eceran', '27', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN JATINUNGGAL', 'DESA SIRNASARI', 'Sumur bor/pompa', '17', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN JATINUNGGAL', 'DESA SIRNASARI', 'Sumur terlindung', '510', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN JATINUNGGAL', 'DESA SIRNASARI', 'Sumur tak terlindung', '64', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN JATINUNGGAL', 'DESA SIRNASARI', 'Mata air terlindung', '43', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN JATINUNGGAL', 'DESA SIRNASARI', 'Mata air tak terlindung', '16', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN UJUNGJAYA', 'DESA UJUNGJAYA', 'Lainnya', '1', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN UJUNGJAYA', 'DESA UJUNGJAYA', 'Air isi ulang', '11', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN UJUNGJAYA', 'DESA UJUNGJAYA', 'Leding meteran', '6', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN UJUNGJAYA', 'DESA UJUNGJAYA', 'Sumur bor/pompa', '29', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN UJUNGJAYA', 'DESA UJUNGJAYA', 'Sumur terlindung', '5', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN UJUNGJAYA', 'DESA UJUNGJAYA', 'Mata air terlindung', '2', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN UJUNGJAYA', 'DESA SUKAMULYA', 'Air kemasan bermerek', '4', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN UJUNGJAYA', 'DESA SUKAMULYA', 'Air isi ulang', '742', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN UJUNGJAYA', 'DESA SUKAMULYA', 'Leding meteran', '10', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN UJUNGJAYA', 'DESA SUKAMULYA', 'Leding eceran', '1', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN UJUNGJAYA', 'DESA SUKAMULYA', 'Sumur bor/pompa', '4', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN UJUNGJAYA', 'DESA SUKAMULYA', 'Sumur terlindung', '1', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN UJUNGJAYA', 'DESA SUKAMULYA', 'Mata air terlindung', '13', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN UJUNGJAYA', 'DESA SAKURJAYA', 'Air kemasan bermerek', '2', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN UJUNGJAYA', 'DESA SAKURJAYA', 'Lainnya', '2', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN UJUNGJAYA', 'DESA SAKURJAYA', 'Air isi ulang', '286', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN UJUNGJAYA', 'DESA SAKURJAYA', 'Leding meteran', '217', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN UJUNGJAYA', 'DESA SAKURJAYA', 'Leding eceran', '12', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN UJUNGJAYA', 'DESA SAKURJAYA', 'Sumur bor/pompa', '417', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN UJUNGJAYA', 'DESA SAKURJAYA', 'Sumur terlindung', '97', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN UJUNGJAYA', 'DESA SAKURJAYA', 'Sumur tak terlindung', '1', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN UJUNGJAYA', 'DESA SAKURJAYA', 'Mata air terlindung', '2', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN UJUNGJAYA', 'DESA PALASARI', 'Air kemasan bermerek', '2', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN UJUNGJAYA', 'DESA PALASARI', 'Lainnya', '13', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN UJUNGJAYA', 'DESA PALASARI', 'Air isi ulang', '845', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN UJUNGJAYA', 'DESA PALASARI', 'Leding meteran', '47', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN UJUNGJAYA', 'DESA PALASARI', 'Leding eceran', '4', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN UJUNGJAYA', 'DESA PALASARI', 'Sumur bor/pompa', '4', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN UJUNGJAYA', 'DESA PALASARI', 'Sumur terlindung', '1', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN UJUNGJAYA', 'DESA PALASARI', 'Mata air terlindung', '3', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN UJUNGJAYA', 'DESA PALABUAN', 'Lainnya', '1', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN UJUNGJAYA', 'DESA PALABUAN', 'Air isi ulang', '122', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN UJUNGJAYA', 'DESA PALABUAN', 'Leding meteran', '309', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN UJUNGJAYA', 'DESA PALABUAN', 'Leding eceran', '5', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN UJUNGJAYA', 'DESA PALABUAN', 'Sumur bor/pompa', '96', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN UJUNGJAYA', 'DESA PALABUAN', 'Sumur terlindung', '57', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN UJUNGJAYA', 'DESA PALABUAN', 'Sumur tak terlindung', '2', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN UJUNGJAYA', 'DESA PALABUAN', 'Mata air terlindung', '24', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN UJUNGJAYA', 'DESA PALABUAN', 'Mata air tak terlindung', '2', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN UJUNGJAYA', 'DESA KUDANGWANGI', 'Air kemasan bermerek', '16', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN UJUNGJAYA', 'DESA KUDANGWANGI', 'Air isi ulang', '542', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN UJUNGJAYA', 'DESA KUDANGWANGI', 'Leding meteran', '2', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN UJUNGJAYA', 'DESA KUDANGWANGI', 'Leding eceran', '5', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN UJUNGJAYA', 'DESA KUDANGWANGI', 'Sumur bor/pompa', '37', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN UJUNGJAYA', 'DESA KUDANGWANGI', 'Sumur terlindung', '42', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN UJUNGJAYA', 'DESA KUDANGWANGI', 'Sumur tak terlindung', '1', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN UJUNGJAYA', 'DESA KUDANGWANGI', 'Mata air terlindung', '2', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN UJUNGJAYA', 'DESA KEBONCAU', 'Air kemasan bermerek', '5', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN UJUNGJAYA', 'DESA KEBONCAU', 'Lainnya', '182', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN UJUNGJAYA', 'DESA KEBONCAU', 'Air isi ulang', '206', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN UJUNGJAYA', 'DESA KEBONCAU', 'Leding meteran', '544', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN UJUNGJAYA', 'DESA KEBONCAU', 'Leding eceran', '9', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN UJUNGJAYA', 'DESA KEBONCAU', 'Sumur terlindung', '1', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN UJUNGJAYA', 'DESA CIPELANG', 'Air isi ulang', '5', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN UJUNGJAYA', 'DESA CIPELANG', 'Leding meteran', '333', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN UJUNGJAYA', 'DESA CIPELANG', 'Leding eceran', '5', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN UJUNGJAYA', 'DESA CIPELANG', 'Mata air terlindung', '275', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN UJUNGJAYA', 'DESA CIBULUH', 'Air kemasan bermerek', '4', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN UJUNGJAYA', 'DESA CIBULUH', 'Air isi ulang', '829', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN UJUNGJAYA', 'DESA CIBULUH', 'Leding meteran', '9', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN UJUNGJAYA', 'DESA CIBULUH', 'Leding eceran', '1', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN UJUNGJAYA', 'DESA CIBULUH', 'Sumur bor/pompa', '21', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA GUDANG', 'Air kemasan bermerek', '3', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA GUDANG', 'Air sungan/danau/waduk', '3', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA GUDANG', 'Lainnya', '34', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA GUDANG', 'Air isi ulang', '240', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA GUDANG', 'Leding meteran', '367', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA GUDANG', 'Leding eceran', '16', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA GUDANG', 'Sumur bor/pompa', '537', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA GUDANG', 'Sumur terlindung', '667', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA GUDANG', 'Sumur tak terlindung', '43', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA GUDANG', 'Mata air terlindung', '266', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA GUDANG', 'Mata air tak terlindung', '7', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA TANJUNGSARI', 'Air kemasan bermerek', '11', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA TANJUNGSARI', 'Air sungan/danau/waduk', '11', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA TANJUNGSARI', 'Lainnya', '53', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA TANJUNGSARI', 'Air isi ulang', '201', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA TANJUNGSARI', 'Leding meteran', '214', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA TANJUNGSARI', 'Leding eceran', '9', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA TANJUNGSARI', 'Sumur bor/pompa', '138', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA TANJUNGSARI', 'Sumur terlindung', '196', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA TANJUNGSARI', 'Sumur tak terlindung', '7', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA TANJUNGSARI', 'Mata air terlindung', '1120', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA TANJUNGSARI', 'Mata air tak terlindung', '8', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA JATISARI', 'Air kemasan bermerek', '123', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA JATISARI', 'Air sungan/danau/waduk', '1', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA JATISARI', 'Lainnya', '4', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA JATISARI', 'Air isi ulang', '279', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA JATISARI', 'Leding meteran', '592', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA JATISARI', 'Leding eceran', '33', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA JATISARI', 'Sumur bor/pompa', '170', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA JATISARI', 'Sumur terlindung', '1284', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA JATISARI', 'Sumur tak terlindung', '17', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA JATISARI', 'Mata air terlindung', '9', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA MARGALUYU', 'Air kemasan bermerek', '23', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA MARGALUYU', 'Air sungan/danau/waduk', '4', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA MARGALUYU', 'Lainnya', '40', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA MARGALUYU', 'Air isi ulang', '284', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA MARGALUYU', 'Leding meteran', '285', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA MARGALUYU', 'Leding eceran', '864', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA MARGALUYU', 'Sumur bor/pompa', '12', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA MARGALUYU', 'Sumur terlindung', '102', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA MARGALUYU', 'Sumur tak terlindung', '3', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA MARGALUYU', 'Mata air terlindung', '141', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA MARGALUYU', 'Mata air tak terlindung', '10', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA KUTAMANDIRI', 'Air kemasan bermerek', '25', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA KUTAMANDIRI', 'Air sungan/danau/waduk', '10', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA KUTAMANDIRI', 'Lainnya', '175', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA KUTAMANDIRI', 'Air isi ulang', '659', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA KUTAMANDIRI', 'Leding meteran', '414', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA KUTAMANDIRI', 'Leding eceran', '275', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA KUTAMANDIRI', 'Sumur bor/pompa', '124', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA KUTAMANDIRI', 'Sumur terlindung', '335', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA KUTAMANDIRI', 'Sumur tak terlindung', '12', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA KUTAMANDIRI', 'Mata air terlindung', '978', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA KUTAMANDIRI', 'Mata air tak terlindung', '8', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA MARGAJAYA', 'Air kemasan bermerek', '1', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA MARGAJAYA', 'Air sungan/danau/waduk', '1', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA MARGAJAYA', 'Lainnya', '40', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA MARGAJAYA', 'Air isi ulang', '87', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA MARGAJAYA', 'Leding meteran', '10', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA MARGAJAYA', 'Leding eceran', '5', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA MARGAJAYA', 'Sumur bor/pompa', '46', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA MARGAJAYA', 'Sumur terlindung', '2605', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA MARGAJAYA', 'Sumur tak terlindung', '102', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA MARGAJAYA', 'Mata air terlindung', '185', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA MARGAJAYA', 'Mata air tak terlindung', '25', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA RAHARJA', 'Air kemasan bermerek', '3', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA RAHARJA', 'Air sungan/danau/waduk', '3', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA RAHARJA', 'Lainnya', '7', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA RAHARJA', 'Air isi ulang', '179', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA RAHARJA', 'Leding meteran', '177', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA RAHARJA', 'Leding eceran', '86', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA RAHARJA', 'Sumur bor/pompa', '22', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA RAHARJA', 'Sumur terlindung', '1125', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA RAHARJA', 'Sumur tak terlindung', '7', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA RAHARJA', 'Mata air terlindung', '273', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA RAHARJA', 'Mata air tak terlindung', '3', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA CIJAMBU', 'Air kemasan bermerek', '4', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA CIJAMBU', 'Air sungan/danau/waduk', '2', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA CIJAMBU', 'Lainnya', '3', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA CIJAMBU', 'Air isi ulang', '8', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA CIJAMBU', 'Leding meteran', '587', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA CIJAMBU', 'Leding eceran', '32', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA CIJAMBU', 'Sumur bor/pompa', '6', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA CIJAMBU', 'Sumur terlindung', '19', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA CIJAMBU', 'Sumur tak terlindung', '4', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA CIJAMBU', 'Mata air terlindung', '876', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA CIJAMBU', 'Mata air tak terlindung', '12', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA PASIGARAN', 'Air kemasan bermerek', '173', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA PASIGARAN', 'Air sungan/danau/waduk', '3', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA PASIGARAN', 'Lainnya', '176', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA PASIGARAN', 'Air isi ulang', '572', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA PASIGARAN', 'Leding meteran', '82', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA PASIGARAN', 'Leding eceran', '17', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA PASIGARAN', 'Sumur bor/pompa', '13', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA PASIGARAN', 'Sumur terlindung', '139', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA PASIGARAN', 'Sumur tak terlindung', '16', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA PASIGARAN', 'Mata air terlindung', '54', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA PASIGARAN', 'Mata air tak terlindung', '7', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA GUNUNG MANIK', 'Air kemasan bermerek', '21', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA GUNUNG MANIK', 'Air sungan/danau/waduk', '2', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA GUNUNG MANIK', 'Air hujan', '1', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA GUNUNG MANIK', 'Lainnya', '38', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA GUNUNG MANIK', 'Air isi ulang', '513', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA GUNUNG MANIK', 'Leding meteran', '331', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA GUNUNG MANIK', 'Leding eceran', '12', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA GUNUNG MANIK', 'Sumur bor/pompa', '84', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA GUNUNG MANIK', 'Sumur terlindung', '2086', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA GUNUNG MANIK', 'Sumur tak terlindung', '32', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA GUNUNG MANIK', 'Mata air terlindung', '153', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA GUNUNG MANIK', 'Mata air tak terlindung', '22', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA KADAKAJAYA', 'Air kemasan bermerek', '2', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA KADAKAJAYA', 'Air sungan/danau/waduk', '1', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA KADAKAJAYA', 'Air hujan', '1', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA KADAKAJAYA', 'Lainnya', '2', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA KADAKAJAYA', 'Air isi ulang', '64', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA KADAKAJAYA', 'Leding meteran', '157', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA KADAKAJAYA', 'Leding eceran', '7', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA KADAKAJAYA', 'Sumur bor/pompa', '1', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA KADAKAJAYA', 'Sumur terlindung', '60', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA KADAKAJAYA', 'Sumur tak terlindung', '4', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA KADAKAJAYA', 'Mata air terlindung', '1051', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA KADAKAJAYA', 'Mata air tak terlindung', '34', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA CINANJUNG', 'Air kemasan bermerek', '9', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA CINANJUNG', 'Air sungan/danau/waduk', '5', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA CINANJUNG', 'Air hujan', '1', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA CINANJUNG', 'Lainnya', '129', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA CINANJUNG', 'Air isi ulang', '454', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA CINANJUNG', 'Leding meteran', '1243', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA CINANJUNG', 'Leding eceran', '40', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA CINANJUNG', 'Sumur bor/pompa', '94', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA CINANJUNG', 'Sumur terlindung', '535', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA CINANJUNG', 'Sumur tak terlindung', '12', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA CINANJUNG', 'Mata air terlindung', '457', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGSARI', 'DESA CINANJUNG', 'Mata air tak terlindung', '12', 'Unit Rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA AWILEGA', 'Air isi ulang', '16', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA AWILEGA', 'Leding meteran', '232', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA AWILEGA', 'Sumur terlindung', '5', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA AWILEGA', 'Sumur tak terlindung', '6', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA AWILEGA', 'Mata air terlindung', '343', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA AWILEGA', 'Mata air tak terlindung', '3', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA BANYUASIH', 'Air kemasan bermerek', '25', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA BANYUASIH', 'Air sungan/danau/waduk', '1', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA BANYUASIH', 'Lainnya', '1', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA BANYUASIH', 'Air isi ulang', '167', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA BANYUASIH', 'Leding meteran', '85', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA BANYUASIH', 'Leding eceran', '5', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA BANYUASIH', 'Sumur bor/pompa', '7', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA BANYUASIH', 'Sumur terlindung', '86', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA BANYUASIH', 'Sumur tak terlindung', '1', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA BANYUASIH', 'Mata air terlindung', '137', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA BANYUASIH', 'Mata air tak terlindung', '8', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA BOROS', 'Air kemasan bermerek', '1', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA BOROS', 'Air isi ulang', '6', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA BOROS', 'Leding meteran', '1', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA BOROS', 'Sumur terlindung', '8', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA BOROS', 'Mata air terlindung', '228', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA BOROS', 'Mata air tak terlindung', '4', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA CIGENTUR', 'Air kemasan bermerek', '2', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA CIGENTUR', 'Air isi ulang', '143', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA CIGENTUR', 'Leding meteran', '7', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA CIGENTUR', 'Leding eceran', '1', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA CIGENTUR', 'Sumur terlindung', '69', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA CIGENTUR', 'Sumur tak terlindung', '1', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA CIGENTUR', 'Mata air terlindung', '1', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA CIPANAS', 'Air kemasan bermerek', '3', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA CIPANAS', 'Air sungan/danau/waduk', '1', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA CIPANAS', 'Lainnya', '1', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA CIPANAS', 'Air isi ulang', '55', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA CIPANAS', 'Leding meteran', '1', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA CIPANAS', 'Sumur bor/pompa', '423', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA CIPANAS', 'Sumur terlindung', '456', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA CIPANAS', 'Sumur tak terlindung', '4', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA CIPANAS', 'Mata air terlindung', '297', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA CIPANAS', 'Mata air tak terlindung', '4', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA GUNTURMEKAR', 'Air isi ulang', '32', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA GUNTURMEKAR', 'Leding meteran', '28', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA GUNTURMEKAR', 'Leding eceran', '4', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA GUNTURMEKAR', 'Sumur bor/pompa', '11', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA GUNTURMEKAR', 'Sumur terlindung', '402', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA GUNTURMEKAR', 'Sumur tak terlindung', '10', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA GUNTURMEKAR', 'Mata air terlindung', '106', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA KERTAHARJA', 'Lainnya', '1', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA KERTAHARJA', 'Air isi ulang', '2', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA KERTAHARJA', 'Leding eceran', '3', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA KERTAHARJA', 'Sumur bor/pompa', '80', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA KERTAHARJA', 'Sumur terlindung', '84', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA KERTAHARJA', 'Sumur tak terlindung', '16', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA KERTAHARJA', 'Mata air terlindung', '85', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA KERTAHARJA', 'Mata air tak terlindung', '15', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA KERTAMEKAR', 'Air isi ulang', '49', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA KERTAMEKAR', 'Sumur terlindung', '32', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA KERTAMEKAR', 'Mata air terlindung', '124', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA MULYAMEKAR', 'Air isi ulang', '99', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA MULYAMEKAR', 'Leding meteran', '227', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA MULYAMEKAR', 'Leding eceran', '44', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA MULYAMEKAR', 'Sumur bor/pompa', '6', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA MULYAMEKAR', 'Sumur terlindung', '180', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA MULYAMEKAR', 'Sumur tak terlindung', '1', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA MULYAMEKAR', 'Mata air terlindung', '142', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA MULYAMEKAR', 'Mata air tak terlindung', '2', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA SUKAMANTRI', 'Air kemasan bermerek', '2', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA SUKAMANTRI', 'Air sungan/danau/waduk', '3', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA SUKAMANTRI', 'Lainnya', '1', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA SUKAMANTRI', 'Air isi ulang', '484', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA SUKAMANTRI', 'Leding meteran', '5', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA SUKAMANTRI', 'Sumur terlindung', '5', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA SUKAMANTRI', 'Sumur tak terlindung', '12', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA SUKAMANTRI', 'Mata air terlindung', '42', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA SUKAMANTRI', 'Mata air tak terlindung', '1083', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA TANJUNGMEKAR', 'Air isi ulang', '9', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA TANJUNGMEKAR', 'Leding eceran', '1', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA TANJUNGMEKAR', 'Sumur bor/pompa', '3', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA TANJUNGMEKAR', 'Sumur terlindung', '637', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA TANJUNGMEKAR', 'Sumur tak terlindung', '19', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA TANJUNGMEKAR', 'Mata air terlindung', '173', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA TANJUNGMEKAR', 'Mata air tak terlindung', '18', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA TANJUNGMULYA', 'Air isi ulang', '4', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA TANJUNGMULYA', 'Sumur bor/pompa', '1', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA TANJUNGMULYA', 'Sumur terlindung', '8', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA TANJUNGMULYA', 'Sumur tak terlindung', '1', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA TANJUNGMULYA', 'Mata air terlindung', '159', 'unit rumah', '2021');
INSERT INTO airminum (kecamatan, desa, sumber, jumlah, satuan, tahun) VALUES ('KECAMATAN TANJUNGKERTA', 'DESA TANJUNGMULYA', 'Mata air tak terlindung', '12', 'unit rumah', '2021');
";
$result = $conn->multi_query($sql);
$conn->close();
?>
<h1>Data template berhasil dimasukkan!</h1>
</body>
</html>